#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : libkdepim
Version  : 23.04.0
Release  : 56
URL      : https://download.kde.org/stable/release-service/23.04.0/src/libkdepim-23.04.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/23.04.0/src/libkdepim-23.04.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/23.04.0/src/libkdepim-23.04.0.tar.xz.sig
Summary  : Libraries for KDE PIM applications
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.0
Requires: libkdepim-data = %{version}-%{release}
Requires: libkdepim-lib = %{version}-%{release}
Requires: libkdepim-license = %{version}-%{release}
Requires: libkdepim-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : akonadi-search-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kcalendarcore-dev
BuildRequires : kcontacts-dev
BuildRequires : kldap-dev
BuildRequires : kmime-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the libkdepim package.
Group: Data

%description data
data components for the libkdepim package.


%package dev
Summary: dev components for the libkdepim package.
Group: Development
Requires: libkdepim-lib = %{version}-%{release}
Requires: libkdepim-data = %{version}-%{release}
Provides: libkdepim-devel = %{version}-%{release}
Requires: libkdepim = %{version}-%{release}

%description dev
dev components for the libkdepim package.


%package lib
Summary: lib components for the libkdepim package.
Group: Libraries
Requires: libkdepim-data = %{version}-%{release}
Requires: libkdepim-license = %{version}-%{release}

%description lib
lib components for the libkdepim package.


%package license
Summary: license components for the libkdepim package.
Group: Default

%description license
license components for the libkdepim package.


%package locales
Summary: locales components for the libkdepim package.
Group: Default

%description locales
locales components for the libkdepim package.


%prep
%setup -q -n libkdepim-23.04.0
cd %{_builddir}/libkdepim-23.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682013533
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1682013533
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libkdepim
cp %{_builddir}/libkdepim-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/libkdepim/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/libkdepim-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/libkdepim/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/libkdepim-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libkdepim/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/libkdepim-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libkdepim/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/libkdepim-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/libkdepim/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
pushd clr-build
%make_install
popd
%find_lang libkdepim

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.kde.addressbook.service.xml
/usr/share/dbus-1/interfaces/org.kde.mailtransport.service.xml
/usr/share/qlogging-categories5/libkdepim.categories
/usr/share/qlogging-categories5/libkdepim.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim5/Libkdepim/Libkdepim/KCheckComboBox
/usr/include/KPim5/Libkdepim/Libkdepim/KWidgetLister
/usr/include/KPim5/Libkdepim/Libkdepim/LineEditCatchReturnKey
/usr/include/KPim5/Libkdepim/Libkdepim/MultiplyingLine
/usr/include/KPim5/Libkdepim/Libkdepim/MultiplyingLineEditor
/usr/include/KPim5/Libkdepim/Libkdepim/ProgressDialog
/usr/include/KPim5/Libkdepim/Libkdepim/ProgressIndicatorLabel
/usr/include/KPim5/Libkdepim/Libkdepim/ProgressManager
/usr/include/KPim5/Libkdepim/Libkdepim/ProgressStatusBarWidget
/usr/include/KPim5/Libkdepim/Libkdepim/StatusbarProgressWidget
/usr/include/KPim5/Libkdepim/libkdepim/kcheckcombobox.h
/usr/include/KPim5/Libkdepim/libkdepim/kdepim_export.h
/usr/include/KPim5/Libkdepim/libkdepim/kwidgetlister.h
/usr/include/KPim5/Libkdepim/libkdepim/lineeditcatchreturnkey.h
/usr/include/KPim5/Libkdepim/libkdepim/multiplyingline.h
/usr/include/KPim5/Libkdepim/libkdepim/multiplyinglineeditor.h
/usr/include/KPim5/Libkdepim/libkdepim/progressdialog.h
/usr/include/KPim5/Libkdepim/libkdepim/progressindicatorlabel.h
/usr/include/KPim5/Libkdepim/libkdepim/progressmanager.h
/usr/include/KPim5/Libkdepim/libkdepim/progressstatusbarwidget.h
/usr/include/KPim5/Libkdepim/libkdepim/statusbarprogresswidget.h
/usr/include/KPim5/Libkdepim/libkdepim_version.h
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimConfig.cmake
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimConfigVersion.cmake
/usr/lib64/cmake/KF5Libkdepim/KPim5LibkdepimTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Libkdepim/KPim5LibkdepimTargets.cmake
/usr/lib64/cmake/KPim5Libkdepim/KPim5LibkdepimConfig.cmake
/usr/lib64/cmake/KPim5Libkdepim/KPim5LibkdepimConfigVersion.cmake
/usr/lib64/cmake/KPim5Libkdepim/KPim5LibkdepimTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim5Libkdepim/KPim5LibkdepimTargets.cmake
/usr/lib64/cmake/KPim5MailTransportDBusService/KPim5MailTransportDBusServiceConfig.cmake
/usr/lib64/cmake/MailTransportDBusService/MailTransportDBusServiceConfig.cmake
/usr/lib64/libKPim5Libkdepim.so
/usr/lib64/qt5/mkspecs/modules/qt_Libkdepim.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKPim5Libkdepim.so.5
/usr/lib64/libKPim5Libkdepim.so.5.23.0
/usr/lib64/qt5/plugins/designer/kdepim5widgets.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libkdepim/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/libkdepim/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/libkdepim/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/libkdepim/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/libkdepim/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libkdepim.lang
%defattr(-,root,root,-)

