#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : libkdepim
Version  : 21.08.1
Release  : 34
URL      : https://download.kde.org/stable/release-service/21.08.1/src/libkdepim-21.08.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/21.08.1/src/libkdepim-21.08.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/21.08.1/src/libkdepim-21.08.1.tar.xz.sig
Summary  : Libraries for KDE PIM applications
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.0
Requires: libkdepim-data = %{version}-%{release}
Requires: libkdepim-lib = %{version}-%{release}
Requires: libkdepim-license = %{version}-%{release}
Requires: libkdepim-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : akonadi-search-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kcalendarcore-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfig-dev
BuildRequires : kconfigwidgets-dev
BuildRequires : kcontacts-dev
BuildRequires : kcoreaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : kldap-dev
BuildRequires : kmime-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : qtbase-dev mesa-dev

%description
No detailed description available

%package data
Summary: data components for the libkdepim package.
Group: Data

%description data
data components for the libkdepim package.


%package dev
Summary: dev components for the libkdepim package.
Group: Development
Requires: libkdepim-lib = %{version}-%{release}
Requires: libkdepim-data = %{version}-%{release}
Provides: libkdepim-devel = %{version}-%{release}
Requires: libkdepim = %{version}-%{release}

%description dev
dev components for the libkdepim package.


%package lib
Summary: lib components for the libkdepim package.
Group: Libraries
Requires: libkdepim-data = %{version}-%{release}
Requires: libkdepim-license = %{version}-%{release}

%description lib
lib components for the libkdepim package.


%package license
Summary: license components for the libkdepim package.
Group: Default

%description license
license components for the libkdepim package.


%package locales
Summary: locales components for the libkdepim package.
Group: Default

%description locales
locales components for the libkdepim package.


%prep
%setup -q -n libkdepim-21.08.1
cd %{_builddir}/libkdepim-21.08.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1630966305
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1630966305
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libkdepim
cp %{_builddir}/libkdepim-21.08.1/CMakePresets.json.license %{buildroot}/usr/share/package-licenses/libkdepim/29fb05b49e12a380545499938c4879440bd8851e
cp %{_builddir}/libkdepim-21.08.1/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/libkdepim/8287b608d3fa40ef401339fd907ca1260c964123
cp %{_builddir}/libkdepim-21.08.1/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libkdepim/e712eadfab0d2357c0f50f599ef35ee0d87534cb
cp %{_builddir}/libkdepim-21.08.1/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/libkdepim/20079e8f79713dce80ab09774505773c926afa2a
cp %{_builddir}/libkdepim-21.08.1/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/libkdepim/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
pushd clr-build
%make_install
popd
%find_lang libkdepim

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.kde.addressbook.service.xml
/usr/share/dbus-1/interfaces/org.kde.mailtransport.service.xml
/usr/share/qlogging-categories5/libkdepim.categories
/usr/share/qlogging-categories5/libkdepim.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/Libkdepim/KCheckComboBox
/usr/include/KF5/Libkdepim/KWidgetLister
/usr/include/KF5/Libkdepim/LineEditCatchReturnKey
/usr/include/KF5/Libkdepim/MultiplyingLine
/usr/include/KF5/Libkdepim/MultiplyingLineEditor
/usr/include/KF5/Libkdepim/ProgressDialog
/usr/include/KF5/Libkdepim/ProgressIndicatorLabel
/usr/include/KF5/Libkdepim/ProgressManager
/usr/include/KF5/Libkdepim/ProgressStatusBarWidget
/usr/include/KF5/Libkdepim/StatusbarProgressWidget
/usr/include/KF5/libkdepim/kcheckcombobox.h
/usr/include/KF5/libkdepim/kdepim_export.h
/usr/include/KF5/libkdepim/kwidgetlister.h
/usr/include/KF5/libkdepim/lineeditcatchreturnkey.h
/usr/include/KF5/libkdepim/multiplyingline.h
/usr/include/KF5/libkdepim/multiplyinglineeditor.h
/usr/include/KF5/libkdepim/progressdialog.h
/usr/include/KF5/libkdepim/progressindicatorlabel.h
/usr/include/KF5/libkdepim/progressmanager.h
/usr/include/KF5/libkdepim/progressstatusbarwidget.h
/usr/include/KF5/libkdepim/statusbarprogresswidget.h
/usr/include/KF5/libkdepim_version.h
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimConfig.cmake
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimConfigVersion.cmake
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Libkdepim/KF5LibkdepimTargets.cmake
/usr/lib64/cmake/MailTransportDBusService/MailTransportDBusServiceConfig.cmake
/usr/lib64/libKF5Libkdepim.so
/usr/lib64/qt5/mkspecs/modules/qt_Libkdepim.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Libkdepim.so.5
/usr/lib64/libKF5Libkdepim.so.5.18.1
/usr/lib64/qt5/plugins/designer/kdepimwidgets.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libkdepim/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/libkdepim/29fb05b49e12a380545499938c4879440bd8851e
/usr/share/package-licenses/libkdepim/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/libkdepim/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/libkdepim/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libkdepim.lang
%defattr(-,root,root,-)

